FROM python:3.11-slim

WORKDIR /app

# Install dependencies
# RUN apt-get update && apt-get install -y libgl1-mesa-glx

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache/pip

# Copy application code
COPY main.py .

# Copy PyTorch model file
COPY tuned_rice_disease_densenet121.pth .

# Expose port (Railway akan override)
EXPOSE 8000

# Start uvicorn server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]